version: "3"
services:
   web:
     image: "${DOCKER_IMAGE}"
     ports:
     - 8001:80
     depends_on:
     - mysql
   mysql:
        image: umajonna9/repo1:mysql
        volumes:
        - db_data:/var/lib/mysql
        environment:
           MYSQL_ROOT_PASSWORD: password
           MYSQL_DATABASE: mydatabase
volumes:
   db_data: {}